<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir)).'/documents';

return array(
    'emberlabs\\gravatarlib\\' => array($vendorDir . '/emberlabs/gravatarlib'),
);
